name: Build Turnip Driver

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-turnip:
    runs-on: ubuntu-latest
    env:
      MESON_BUILD_DIR: build

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

    
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential python3-pip ninja-build libdrm-dev libexpat1-dev \
          libx11-dev libxext-dev libxdamage-dev libxfixes-dev libxcb1-dev libxcb-dri2-0-dev \
          libxcb-dri3-dev libxcb-glx0-dev libxcb-present-dev python3-mako

      - name: Upgrade Meson and build tools
        run: |
          pip install --upgrade pip setuptools wheel ninja
          pip install meson==1.4.1

      - name: Configure build
        run: |
          mkdir -p $MESON_BUILD_DIR
          cd $MESON_BUILD_DIR
          meson setup --prefix=/usr \
                      -Dgallium-drivers=turnip \
                      -Dvulkan-drivers=freedreno \
                      -Dbuildtype=release ..

      - name: Compile Turnip
        run: ninja -C $MESON_BUILD_DIR

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: turnip-driver
          path: ${{ env.MESON_BUILD_DIR }}
